import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";
import Providers from "./providers";

export const metadata: Metadata = {
  title: "shopsphere",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          {/* Navbar */}
          
          {/* Main App */}
          <div className="container max-w-7xl mx-auto pt-30 min-h-screen flex">
            <Toaster />
            {children}
          </div>
          {/* Footer */}
         
        </Providers>
      </body>
    </html>
  );
}
