import Navbar from "@/components/navbar";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";
import Providers from "./providers";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "shopsphere",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans", inter.variable)} suppressHydrationWarning>
      <body>
        <Providers>
          {/* Navbar */}

          {/* Main App */}
          <div className=" min-h-screen">
            <Navbar />
            <div className="container max-w-7xl mx-auto">{children}</div>
            <Toaster />
          </div>
          {/* Footer */}
        </Providers>
      </body>
    </html>
  );
}
