spring.application.name=eCommerce
jwt.secret=yNcWGArQWpoh4lHACl/cbhnWdgCv9ML92Rq+SMnl3zc=
jwt.expiry=604800000
# SQL connection settings
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce?user=postgres&password=StormVenom2
spring.jpa.hibernate.ddl-auto=update
spring.datasource.hikari.connection-timeout=30000
# JPA settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
# Data Seed settings
spring.jackson.deserialization.fail-on-unknown-properties=false
# Jpa batching
spring.jpa.properties.hibernate.jdbc.batch_size=100
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true